# 6.0 required for FBSnapshotTestCase
platform :ios, '7.0'

target "NUIDemo" do
  pod "NUIParse", :git => "https://github.com/tombenner/NUIParse"
end

target "NUITests" do
  pod 'FBSnapshotTestCase'
end
